---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.3
before_install: gem install bundler -v 1.16.4
env:
  global:
    - CC_TEST_REPORTER_ID=42769facf6def4b6d345dbb94ca758522b183000544106a5ef973663bd919aea
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT